### ISSUE TITLE
Adding an option to customize sections

### ISSUE THREAD

**Issue by HDouss** [Decathlon/release-notes-generator-action#11]
Thanks for this action.
Spring github release notes generator supports sections customization. It would be nice to have this option in the github action.

**Comment by mmornati** [comment]
Hey @HDouss, sorry for the late response, we were all hardly working on lot of stuff due to the period.

You are not the first one asking for this (even if it is not visible in the repository). 

I will take it and the function as it is really useful. I thought we did at the beginning but rechecking I see it was not.
I'm working on it right now...
